### ISSUE TITLE
Check compatibility with more recent versions of PHP.

### ISSUE THREAD

**Issue by kherge** [kherge-php/json#12]
Add the following versions to the test matrix:

- 7.2
- 7.3
- 7.4

**Comment by kherge** [comment]
Build failed with version 4 of json-schema in PHP 7.4. I am going to take this as an opportunity to create v3 of this library and drop support for outdated versions of PHP and dependencies.

**Comment by peter279k** [comment]
To be compatibility, it seems that the deprecated warning message is as follows on `php-7.4` test:

```
Deprecated: Array and string offset access syntax with curly braces is deprecated in.......
```

The array and string offset should change into `[]`, not `{}`.

**Comment by peter279k** [comment]
The dependency should not use `5.0.0` on `php-7.4` version and only using `^5.0.0` instead.

The related PR is available [here](https://github.com/justinrainbow/json-schema/pull/607).

**Comment by kherge** [comment]
Version 3 [tagged](https://github.com/kherge-php/json/compare/2.1.1...3.0.0) and released.
