### ISSUE TITLE
herrera-io/json is abandoned

### ISSUE THREAD

**Issue by peter279k** [kherge-php/json#9]
When I visit the [herrera-io/json](https://packagist.org/packages/herrera-io/json), it's abandoned.

And it looks like the replaced package is `kherge/json`.

@kherge, does the abandoned package have any suggestion about replaced package?

**Comment by kherge** [comment]
Hi @peter279k, I am not sure I understand the question.

If you are looking for a way to upgrade to `kherge/json`, I would recommend the following:

1. Replace the package `herrera-io/json` with `kherge/json`.
2. Replace class references `Herrera\Json\Json` with `KHerGe\JSON\JSON`.

Other than that, the API should be identical.

**Comment by peter279k** [comment]
Hi @kherge, I look for the way to upgrade my `kherge/json` package.

When I install some dependencies, I've found that following warning message:

```
Package herrera-io/version is abandoned, you should avoid using it. No replacement was suggested.
Package herrera-io/json is abandoned, you should avoid using it. Use kherge/json instead.
Package herrera-io/phar-update is abandoned, you should avoid using it. No replacement was suggested.
```

That's why I create this issue to ask for help :).

I think it should have some suggested message and the sample messages are as follows:

```
Package apigen/theme-bootstrap is abandoned, you should avoid using it. Use apigen/apigen instead.
```

And it can help developers to know how to replace the package.

**Comment by kherge** [comment]
I apologize, but I am certain I am misunderstanding something. In the output you provided, Composer suggests an alternative:

<pre>
Package herrera-io/version is abandoned, you should avoid using it. No replacement was suggested.
<strong>Package herrera-io/json is abandoned, you should avoid using it. Use kherge/json instead.</strong>
Package herrera-io/phar-update is abandoned, you should avoid using it. No replacement was suggested.
</pre>

The Packagist website also mentions this.

<img width="646" alt="Capture" src="https://user-images.githubusercontent.com/9122157/73371702-eab63e00-426a-11ea-9af5-774c6ea9b7d9.PNG">

**Comment by peter279k** [comment]
Ok. Thanks, @kherge.
